name: Test and publish charm

# On push to a "special" branch, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# where a "special" branch is one of main/master or track/**, as
# by convention these branches are the source for a corresponding
# charmhub edge channel.

on:
  workflow_call:
    inputs:
      integration-test-extra-arguments:
        description: Additional arguments to pass to the integration tests
        type: string
      integration-test-pre-run-script:
        description: Path to the bash script to be run before the integration tests
        type: string
      integration-test-provider:
        description: Actions operator provider for the integration tests as per https://github.com/charmed-kubernetes/actions-operator#usage
        type: string
        default: microk8s
      integration-test-series:
        description: List of series to run the integration tests in JSON format, i.e. '["jammy", "focal"]'. Each element will be passed to pytest through tox as --series argument
        type: string
        default: '[""]'
      integration-test-modules:
        description: List of testing modules to run the tests in JSON format, i.e. '["foo", "bar"]'. Each element will be passed to pytest through tox as -k argument
        type: string
        default: '[""]'
      setup-devstack-swift:
        description: Use setup-devstack-swift action to prepare a swift server for integration tests.
        type: boolean
        default: false

jobs:
  tests:
    name: Run tests
    uses: ./.github/workflows/test.yaml
    secrets: inherit
